/* eslint-disable no-unused-vars */
const createCounter = require('./functions/closure/createCounter');
const repeatFunction = require('./functions/closure/repeatFunction');
const filterUniqueWords = require('./functions/composition/filterUniqueWords');
const getAverageGrade = require('./functions/composition/getAverageGrade');
const getFullName = require('./functions/composition/getFullName');
const fibonacciCache = require('./functions/extra/fibonacciCache');
const fibonacciTale = require('./functions/extra/fibonacciTail');
const fibonacciGenerator = require('./functions/generators/fibonacciGenerator');
const lazyMap = require('./functions/generators/lazyMap');
const calculateDiscountedPrice = require('./functions/pureFunctions/calculateDiscountedPrice');
const calculateTotalPrice = require('./functions/pureFunctions/calculateTotalPrice');
const calculateFactorial = require('./functions/recursion/calculateFactorial');
const power = require('./functions/recursion/power');
