/* eslint-disable no-unused-vars */
const createCounter = require('./functions/task3-closure/createCounter');
const repeatFunction = require('./functions/task3-closure/repeatFunction');
const filterUniqueWords = require('./functions/task2-composition/filterUniqueWords');
const getAverageGrade = require('./functions/task2-composition/getAverageGrade');
const getFullName = require('./functions/task2-composition/getFullName');
const fibonacciCache = require('./functions/extra/fibonacciCache');
const fibonacciTale = require('./functions/extra/fibonacciTail');
const fibonacciGenerator = require('./functions/task5-generators/fibonacciGenerator');
const lazyMap = require('./functions/task5-generators/lazyMap');
const calculateDiscountedPrice = require('./functions/task1-pureFunctions/calculateDiscountedPrice');
const calculateTotalPrice = require('./functions/task1-pureFunctions/calculateTotalPrice');
const calculateFactorial = require('./functions/task4-recursion/calculateFactorial');
const power = require('./functions/task4-recursion/power');
